version: "2.1"
services:
    backend:
        depends_on:
            - mariadb
        container_name: backend
        build: ./backend/.
        ports:
            - 8080:80
        restart: always
            
    mariadb:
        image: linuxserver/mariadb
        container_name: mariadb
        environment: 
            - PUID=1000
            - PGID=1000
            - MYSQL_ROOT_PASSWORD="test"
            - MYSQL_DATABASE="wecode2020"
            - MYSQL_USER="wecode"
            - MYSQL_PASSWORD="wecode2020"
        ports:
            - 3306:3306
        volumes: 
            - /var/www/html/mysql:/config
        restart: unless-stopped

    frontend:
        depends_on:
            - backend
        container_name: frontend
        # image: my-node:latest
        build: ./frontend/.
        container_name: react
        ports:
            - 80:3000
        restart: always